/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaitingRouteImport } from './routes/waiting'
import { Route as TutorialRouteImport } from './routes/tutorial'
import { Route as SwipeRouteImport } from './routes/swipe'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as ResultRouteImport } from './routes/result'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as HatchRouteImport } from './routes/hatch'
import { Route as FriendRouteImport } from './routes/friend'
import { Route as CompleteRouteImport } from './routes/complete'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FriendIndexRouteImport } from './routes/friend.index'
import { Route as ResultSessionIdRouteImport } from './routes/result_.$sessionId'
import { Route as FriendSwipeRouteImport } from './routes/friend.swipe'
import { Route as FriendCompleteRouteImport } from './routes/friend.complete'

const WaitingRoute = WaitingRouteImport.update({
  id: '/waiting',
  path: '/waiting',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorialRoute = TutorialRouteImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => rootRouteImport,
} as any)
const SwipeRoute = SwipeRouteImport.update({
  id: '/swipe',
  path: '/swipe',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const HatchRoute = HatchRouteImport.update({
  id: '/hatch',
  path: '/hatch',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendRoute = FriendRouteImport.update({
  id: '/friend',
  path: '/friend',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteRoute = CompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendIndexRoute = FriendIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FriendRoute,
} as any)
const ResultSessionIdRoute = ResultSessionIdRouteImport.update({
  id: '/result_/$sessionId',
  path: '/result/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendSwipeRoute = FriendSwipeRouteImport.update({
  id: '/swipe',
  path: '/swipe',
  getParentRoute: () => FriendRoute,
} as any)
const FriendCompleteRoute = FriendCompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => FriendRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/complete': typeof CompleteRoute
  '/friend': typeof FriendRouteWithChildren
  '/hatch': typeof HatchRoute
  '/invite': typeof InviteRoute
  '/profile': typeof ProfileRoute
  '/result': typeof ResultRoute
  '/stats': typeof StatsRoute
  '/swipe': typeof SwipeRoute
  '/tutorial': typeof TutorialRoute
  '/waiting': typeof WaitingRoute
  '/friend/complete': typeof FriendCompleteRoute
  '/friend/swipe': typeof FriendSwipeRoute
  '/result/$sessionId': typeof ResultSessionIdRoute
  '/friend/': typeof FriendIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/complete': typeof CompleteRoute
  '/hatch': typeof HatchRoute
  '/invite': typeof InviteRoute
  '/profile': typeof ProfileRoute
  '/result': typeof ResultRoute
  '/stats': typeof StatsRoute
  '/swipe': typeof SwipeRoute
  '/tutorial': typeof TutorialRoute
  '/waiting': typeof WaitingRoute
  '/friend/complete': typeof FriendCompleteRoute
  '/friend/swipe': typeof FriendSwipeRoute
  '/result/$sessionId': typeof ResultSessionIdRoute
  '/friend': typeof FriendIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/complete': typeof CompleteRoute
  '/friend': typeof FriendRouteWithChildren
  '/hatch': typeof HatchRoute
  '/invite': typeof InviteRoute
  '/profile': typeof ProfileRoute
  '/result': typeof ResultRoute
  '/stats': typeof StatsRoute
  '/swipe': typeof SwipeRoute
  '/tutorial': typeof TutorialRoute
  '/waiting': typeof WaitingRoute
  '/friend/complete': typeof FriendCompleteRoute
  '/friend/swipe': typeof FriendSwipeRoute
  '/result_/$sessionId': typeof ResultSessionIdRoute
  '/friend/': typeof FriendIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/complete'
    | '/friend'
    | '/hatch'
    | '/invite'
    | '/profile'
    | '/result'
    | '/stats'
    | '/swipe'
    | '/tutorial'
    | '/waiting'
    | '/friend/complete'
    | '/friend/swipe'
    | '/result/$sessionId'
    | '/friend/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/complete'
    | '/hatch'
    | '/invite'
    | '/profile'
    | '/result'
    | '/stats'
    | '/swipe'
    | '/tutorial'
    | '/waiting'
    | '/friend/complete'
    | '/friend/swipe'
    | '/result/$sessionId'
    | '/friend'
  id:
    | '__root__'
    | '/'
    | '/complete'
    | '/friend'
    | '/hatch'
    | '/invite'
    | '/profile'
    | '/result'
    | '/stats'
    | '/swipe'
    | '/tutorial'
    | '/waiting'
    | '/friend/complete'
    | '/friend/swipe'
    | '/result_/$sessionId'
    | '/friend/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompleteRoute: typeof CompleteRoute
  FriendRoute: typeof FriendRouteWithChildren
  HatchRoute: typeof HatchRoute
  InviteRoute: typeof InviteRoute
  ProfileRoute: typeof ProfileRoute
  ResultRoute: typeof ResultRoute
  StatsRoute: typeof StatsRoute
  SwipeRoute: typeof SwipeRoute
  TutorialRoute: typeof TutorialRoute
  WaitingRoute: typeof WaitingRoute
  ResultSessionIdRoute: typeof ResultSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waiting': {
      id: '/waiting'
      path: '/waiting'
      fullPath: '/waiting'
      preLoaderRoute: typeof WaitingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutorial': {
      id: '/tutorial'
      path: '/tutorial'
      fullPath: '/tutorial'
      preLoaderRoute: typeof TutorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swipe': {
      id: '/swipe'
      path: '/swipe'
      fullPath: '/swipe'
      preLoaderRoute: typeof SwipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hatch': {
      id: '/hatch'
      path: '/hatch'
      fullPath: '/hatch'
      preLoaderRoute: typeof HatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friend': {
      id: '/friend'
      path: '/friend'
      fullPath: '/friend'
      preLoaderRoute: typeof FriendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete': {
      id: '/complete'
      path: '/complete'
      fullPath: '/complete'
      preLoaderRoute: typeof CompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friend/': {
      id: '/friend/'
      path: '/'
      fullPath: '/friend/'
      preLoaderRoute: typeof FriendIndexRouteImport
      parentRoute: typeof FriendRoute
    }
    '/result_/$sessionId': {
      id: '/result_/$sessionId'
      path: '/result/$sessionId'
      fullPath: '/result/$sessionId'
      preLoaderRoute: typeof ResultSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friend/swipe': {
      id: '/friend/swipe'
      path: '/swipe'
      fullPath: '/friend/swipe'
      preLoaderRoute: typeof FriendSwipeRouteImport
      parentRoute: typeof FriendRoute
    }
    '/friend/complete': {
      id: '/friend/complete'
      path: '/complete'
      fullPath: '/friend/complete'
      preLoaderRoute: typeof FriendCompleteRouteImport
      parentRoute: typeof FriendRoute
    }
  }
}

interface FriendRouteChildren {
  FriendCompleteRoute: typeof FriendCompleteRoute
  FriendSwipeRoute: typeof FriendSwipeRoute
  FriendIndexRoute: typeof FriendIndexRoute
}

const FriendRouteChildren: FriendRouteChildren = {
  FriendCompleteRoute: FriendCompleteRoute,
  FriendSwipeRoute: FriendSwipeRoute,
  FriendIndexRoute: FriendIndexRoute,
}

const FriendRouteWithChildren =
  FriendRoute._addFileChildren(FriendRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompleteRoute: CompleteRoute,
  FriendRoute: FriendRouteWithChildren,
  HatchRoute: HatchRoute,
  InviteRoute: InviteRoute,
  ProfileRoute: ProfileRoute,
  ResultRoute: ResultRoute,
  StatsRoute: StatsRoute,
  SwipeRoute: SwipeRoute,
  TutorialRoute: TutorialRoute,
  WaitingRoute: WaitingRoute,
  ResultSessionIdRoute: ResultSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
